version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
    open-pull-requests-limit: 99
    assignees:
      - ffflorian
    versioning-strategy: increase
    cooldown:
      default-days: 5
      exclude:
        - '@ffflorian/*'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: monthly
    open-pull-requests-limit: 99
    assignees:
      - ffflorian
