version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '07:00'
      timezone: 'Europe/Berlin'
    open-pull-requests-limit: 99
    assignees:
      - ffflorian
    versioning-strategy: increase
    ignore:
      - dependency-name: '@types/node'
        versions:
          - '> 16.x'
      - dependency-name: 'husky'
        versions:
          - '> 4.x'
      - dependency-name: 'react-scripts'
        versions:
          - '> 4.x'
