name: Build, test, deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}
jobs:
  build_test_deploy:
    permissions:
      contents: read
    name: Build, test and deploy
    runs-on: ubuntu-latest
