name: Build, test, and release

permissions: {}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_test_release:
    name: Build, test and release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: 24.x
          cache: yarn

      - name: Build, lint, and test
        run: |
          yarn --immutable
          yarn lint
          yarn test
          yarn build

      - name: Release
        if: github.event_name == 'push'
        run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
