name: Deploy

permissions: {}

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy latest image
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Deploy
        uses: ffflorian/actions/coolify-deploy@ab061ffdaad5753c96129a0784cc23e9f1b18350
        with:
          domain: ${{ secrets.COOLIFY_DOMAIN }}
          token: ${{ secrets.COOLIFY_TOKEN }}
          uuid: ${{ secrets.COOLIFY_UUID }}
