name: Deploy

permissions: {}

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy latest image
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    steps:
      - name: Deploy
        uses: ffflorian/actions/coolify-deploy@9c7842ec0251a5890f0ca9ef22deed8dbc4ea9fa
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          domain: ${{ secrets.COOLIFY_DOMAIN }}
          token: ${{ secrets.COOLIFY_TOKEN }}
          uuid: ${{ secrets.COOLIFY_UUID }}
