name: Deploy

permissions: {}

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy latest image
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Deploy
        uses: ffflorian/actions/coolify-deploy@86a6f4fba506628f07585dcd4010e05f2396c25a
        with:
          domain: ${{ secrets.COOLIFY_DOMAIN }}
          token: ${{ secrets.COOLIFY_TOKEN }}
          uuid: ${{ secrets.COOLIFY_UUID }}
