name: Force Release

permissions: {}

on:
  workflow_dispatch:

jobs:
  force-release:
    name: Force release
    permissions:
      contents: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - uses: ffflorian/actions/force-release@3c7c457eb4a6b2858cd12bd87c4d076b5ca1c22f
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          git_authorship: 'Florian Imdahl <git@ffflorian.de>'
