name: Push to master

on:
  push:
    branches:
      - master

jobs:
  build_test_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: |
          yarn
          yarn lint
          yarn test
          yarn dist
        env:
          CI: true
          GIT_AUTHOR_NAME: ffflobot
          GIT_AUTHOR_EMAIL: ffflobot@users.noreply.github.com
          GIT_COMMITTER_NAME: ffflobot
          GIT_COMMITTER_EMAIL: ffflobot@users.noreply.github.com
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: |
          contains(github.event.commits[0].message, '[skip ci]') == false &&
          contains(github.event.commits[0].message, '[ci skip]') == false
      - uses: "ffflorian/actions/gh-pages@v1.0.0"
        with:
          args: --dotfiles --dist build --message Publish
        env:
          GH_USER: ffflobot
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        if: |
          contains(github.event.commits[0].message, '[skip ci]') == false &&
          contains(github.event.commits[0].message, '[ci skip]') == false
