name: Build

on:
  push:
    branches:
      - main

jobs:
  build_test_deploy:
    name: Build, test and deploy
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, '[ci skip]') &&
      !contains(github.event.head_commit.message, '[skip ci]')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Yarn cache
        uses: c-hive/gha-yarn-cache@v1
      - name: Build and test
        run: |
          yarn
          yarn lint
          yarn test
          yarn dist
      - name: Deploy
        run: |
          REPO_URL="$(git remote get-url origin | sed -n "s/https:\/\/github.com\//https:\/\/${GIT_AUTHOR_NAME}:${GH_TOKEN}@github.com\//p")"
          yarn deploy -u "${GIT_AUTHOR_NAME} <${GIT_AUTHOR_EMAIL}>" -r "${REPO_URL}"
        env:
          CI: true
          GIT_AUTHOR_NAME: ffflobot
          GIT_AUTHOR_EMAIL: ffflobot@users.noreply.github.com
          GIT_COMMITTER_NAME: ffflobot
          GIT_COMMITTER_EMAIL: ffflobot@users.noreply.github.com
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
