name: Push to master

on:
  push:
    branches:
      - master

jobs:
  build_test_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: |
          yarn
          yarn lint
          yarn test
          yarn dist
          REPO_URL="$(git remote get-url origin | sed -n "s/https:\/\/github.com\//https:\/\/${GIT_AUTHOR_NAME}:${GH_TOKEN}@github.com\//p")"
          yarn deploy -u "ffflobot <ffflobot@users.noreply.github.com>" -r "${REPO_URL}"
        env:
          CI: true
          GH_USER: ffflorian
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        if: |
          contains(github.event.commits[0].message, '[skip ci]') == false &&
          contains(github.event.commits[0].message, '[ci skip]') == false
